language: c
env:
  - features=""
  - features="--enable-debug"
  - features="--enable-xmlreport"
  - features="--enable-autoref"
  - features="--enable-history"
  - features="--enable-clusters"
  - features="--enable-tclfilter"
  - features="--enable-tmux"
  - features="--enable-debug --enable-xmlreport"
  - features="--enable-autoref --enable-debug"
  - features="--enable-debug --enable-history"
  - features="--enable-clusters --enable-debug"
  - features="--enable-debug --enable-tclfilter"
  - features="--enable-debug --enable-tmux"
  - features="--enable-autoref --enable-xmlreport"
  - features="--enable-history --enable-xmlreport"
  - features="--enable-clusters --enable-xmlreport"
  - features="--enable-tclfilter --enable-xmlreport"
  - features="--enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-history"
  - features="--enable-autoref --enable-clusters"
  - features="--enable-autoref --enable-tclfilter"
  - features="--enable-autoref --enable-tmux"
  - features="--enable-clusters --enable-history"
  - features="--enable-history --enable-tclfilter"
  - features="--enable-history --enable-tmux"
  - features="--enable-clusters --enable-tclfilter"
  - features="--enable-clusters --enable-tmux"
  - features="--enable-tclfilter --enable-tmux"
  - features="--enable-autoref --enable-debug --enable-xmlreport"
  - features="--enable-debug --enable-history --enable-xmlreport"
  - features="--enable-clusters --enable-debug --enable-xmlreport"
  - features="--enable-debug --enable-tclfilter --enable-xmlreport"
  - features="--enable-debug --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-debug --enable-history"
  - features="--enable-autoref --enable-clusters --enable-debug"
  - features="--enable-autoref --enable-debug --enable-tclfilter"
  - features="--enable-autoref --enable-debug --enable-tmux"
  - features="--enable-clusters --enable-debug --enable-history"
  - features="--enable-debug --enable-history --enable-tclfilter"
  - features="--enable-debug --enable-history --enable-tmux"
  - features="--enable-clusters --enable-debug --enable-tclfilter"
  - features="--enable-clusters --enable-debug --enable-tmux"
  - features="--enable-debug --enable-tclfilter --enable-tmux"
  - features="--enable-autoref --enable-history --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-xmlreport"
  - features="--enable-autoref --enable-tclfilter --enable-xmlreport"
  - features="--enable-autoref --enable-tmux --enable-xmlreport"
  - features="--enable-clusters --enable-history --enable-xmlreport"
  - features="--enable-history --enable-tclfilter --enable-xmlreport"
  - features="--enable-history --enable-tmux --enable-xmlreport"
  - features="--enable-clusters --enable-tclfilter --enable-xmlreport"
  - features="--enable-clusters --enable-tmux --enable-xmlreport"
  - features="--enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-history"
  - features="--enable-autoref --enable-history --enable-tclfilter"
  - features="--enable-autoref --enable-history --enable-tmux"
  - features="--enable-autoref --enable-clusters --enable-tclfilter"
  - features="--enable-autoref --enable-clusters --enable-tmux"
  - features="--enable-autoref --enable-tclfilter --enable-tmux"
  - features="--enable-clusters --enable-history --enable-tclfilter"
  - features="--enable-clusters --enable-history --enable-tmux"
  - features="--enable-history --enable-tclfilter --enable-tmux"
  - features="--enable-clusters --enable-tclfilter --enable-tmux"
  - features="--enable-autoref --enable-debug --enable-history --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-xmlreport"
  - features="--enable-autoref --enable-debug --enable-tclfilter --enable-xmlreport"
  - features="--enable-autoref --enable-debug --enable-tmux --enable-xmlreport"
  - features="--enable-clusters --enable-debug --enable-history --enable-xmlreport"
  - features="--enable-debug --enable-history --enable-tclfilter --enable-xmlreport"
  - features="--enable-debug --enable-history --enable-tmux --enable-xmlreport"
  - features="--enable-clusters --enable-debug --enable-tclfilter --enable-xmlreport"
  - features="--enable-clusters --enable-debug --enable-tmux --enable-xmlreport"
  - features="--enable-debug --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-history"
  - features="--enable-autoref --enable-debug --enable-history --enable-tclfilter"
  - features="--enable-autoref --enable-debug --enable-history --enable-tmux"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-tclfilter"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-tmux"
  - features="--enable-autoref --enable-debug --enable-tclfilter --enable-tmux"
  - features="--enable-clusters --enable-debug --enable-history --enable-tclfilter"
  - features="--enable-clusters --enable-debug --enable-history --enable-tmux"
  - features="--enable-debug --enable-history --enable-tclfilter --enable-tmux"
  - features="--enable-clusters --enable-debug --enable-tclfilter --enable-tmux"
  - features="--enable-autoref --enable-clusters --enable-history --enable-xmlreport"
  - features="--enable-autoref --enable-history --enable-tclfilter --enable-xmlreport"
  - features="--enable-autoref --enable-history --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-tclfilter --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-clusters --enable-history --enable-tclfilter --enable-xmlreport"
  - features="--enable-clusters --enable-history --enable-tmux --enable-xmlreport"
  - features="--enable-history --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-clusters --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-history --enable-tclfilter"
  - features="--enable-autoref --enable-clusters --enable-history --enable-tmux"
  - features="--enable-autoref --enable-history --enable-tclfilter --enable-tmux"
  - features="--enable-autoref --enable-clusters --enable-tclfilter --enable-tmux"
  - features="--enable-clusters --enable-history --enable-tclfilter --enable-tmux"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-history --enable-xmlreport"
  - features="--enable-autoref --enable-debug --enable-history --enable-tclfilter --enable-xmlreport"
  - features="--enable-autoref --enable-debug --enable-history --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-tclfilter --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-debug --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-clusters --enable-debug --enable-history --enable-tclfilter --enable-xmlreport"
  - features="--enable-clusters --enable-debug --enable-history --enable-tmux --enable-xmlreport"
  - features="--enable-debug --enable-history --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-clusters --enable-debug --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-history --enable-tclfilter"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-history --enable-tmux"
  - features="--enable-autoref --enable-debug --enable-history --enable-tclfilter --enable-tmux"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-tclfilter --enable-tmux"
  - features="--enable-clusters --enable-debug --enable-history --enable-tclfilter --enable-tmux"
  - features="--enable-autoref --enable-clusters --enable-history --enable-tclfilter
    --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-history --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-history --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-clusters --enable-history --enable-tclfilter --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-history --enable-tclfilter
    --enable-tmux"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-history --enable-tclfilter
    --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-history --enable-tmux
    --enable-xmlreport"
  - features="--enable-autoref --enable-debug --enable-history --enable-tclfilter --enable-tmux
    --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-tclfilter --enable-tmux
    --enable-xmlreport"
  - features="--enable-clusters --enable-debug --enable-history --enable-tclfilter --enable-tmux
    --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-history --enable-tclfilter
    --enable-tmux"
  - features="--enable-autoref --enable-clusters --enable-history --enable-tclfilter
    --enable-tmux --enable-xmlreport"
  - features="--enable-autoref --enable-clusters --enable-debug --enable-history --enable-tclfilter
    --enable-tmux --enable-xmlreport"

addons:
  apt:
    packages:
      - automake
      - libpopt-dev
      - libglib2.0-dev
      - libncursesw5-dev
      - tcl8.5-dev
      - libxml2-dev
      - libconfig-dev
      - gettext
      - autopoint

script:
  - autoreconf -if
  - "./configure $features"
  - make
  - "./src/apt-dater -v"

after_success:
  - make dist
  - export DIST_FILE=$(ls apt-dater-*.tar.gz)
  - export SHA256_FILE=$DIST_FILE.sha256
  - shasum -a 256 $DIST_FILE > $SHA256_FILE

deploy:
  provider: releases
  api_key:
    secure: JHYZEopHGbHDYG9MdGJY/hBFvMju7v+YxzyJsLkEfWTJQUMCvV9uDG1JrJnl5UtTEfT7iciZ+wA9CKKaTBO6zXREkQqcRi6pH6Hw6yG6Buscb6o0bGVucveJKHYtjB5CFPNCrJIIX2KirNmuPYtjthyuwHjOFgaw4y5JWc5CvxTNWC6M6pLQOV8nidokuWs4HkjwjE3e4fAZ6C9HAJTZ6hrD47TAYwdFz4L4vMDacznHcz4CcypTBa1eRYmV4UrbhxS4Xktvhaz99XSgWZHeHHp/qK8vi6LGQ/pKz8a+33C+grBz4f3ra4XzZlVzwthi2ATXb5FjU4tF6rKYvccF6VJvG3b/BHSU7OQYbwSGqh3v5iyVgp3CnePM5XwOYMN++eQM57SzulVmukqDLrCa3Q0bNfKANKKMDour0BG/yQYRKyNJAdcA2TBx3nIBKCIS634HJL0dxXesIGSjgMovgJFS6AIMz6ETzv4EZU7lGhh1dSywH0Lq6pNnc826WRiZ0YIjGTogClQjMdGqAxh72bGIcb7eiD7c0t0V091R8Qcgyg4ankXss3kNyI/CU/BffcTsWHc0t18rygpyNDrGzOVooanpWz1JXGngo2UsolGu/3kVumTZlagjWJy65nNYjJi5PGC8yT8Y4IsqmZhByUr9GrC2gv0MYdhPPNFET0o=
  file:
    - $DIST_FILE
    - $SHA256_FILE
  skip_cleanup: true
  on:
    repo: twouters/apt-dater
    branch: autotools-cleanup
